#!/bin/bash

# Written by Frank Heckenbach <f.heckenbach@fh-soft.de> 2012-2016.
#
# This program is in the public domain where legally possible.
# Otherwise, this program is free software; as a special exception
# the author gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# Save the terminal on stdin (if available) in a new FD
# so individual interactive jobs can use it in a safe way
# when a parallel make invalidates their own stdin.
if [ -t 0 ]; then
  # bash feature: allocate a new FD
  exec {SHARED_TERMINAL_FD}<&0
  export SHARED_TERMINAL_FD
fi

exec make "$@"
